### ISSUE TITLE
[Feature request] Use 'shadow' border

### ISSUE THREAD

**Issue by Bekaboo** [SmiteshP/nvim-navbuddy#10]
Firstly, thank you for making this awesome plugin!

The plugin works pretty good with little configuration, and this is a only request of aesthetic concern. I notice that when I use 'shadow' as the border style, the floating window looks weird:

![image](https://user-images.githubusercontent.com/76579810/227814490-936e2198-855b-4f16-9e47-b1e7f67992f7.png)

It seems that there are actually two floating windows side by side, resulting in the gap in the middle. Can we make it more coherent? Thanks in advance!

**Comment by SmiteshP** [comment]
Hi @Bekaboo !
I tried working out this issue. Not able to figure out why the gap in middle appears. Also nui.nvim only allows setting border_chars, and only using that its not possible to have the "floating" effect in bottom_left and top_right corners. Will need some manual highlighting in those corners I guess. Maybe this could be resolved as part of [this issue ](https://github.com/MunifTanjim/nui.nvim/issues/249). Will remove mentions of shadow style in docs until then.
