### ISSUE TITLE
Show jsx in outline

### ISSUE THREAD

**Issue by TxHawks** [SmiteshP/nvim-navbuddy#11]
Hey, great work on this. Super useful and comfortable to work with. 
symbols-outline.nvim has a very useful feature when working with JavaScript and TypeScript, where it will also show the outline of JSX elements, which can be super useful. See [simrat39/symbols-outline.nvim#144](/simrat39/symbols-outline.nvim/pull/144) and [#169](/simrat39/symbols-outline.nvim/pull/169) for the pull requests implementing it.

Could this possibly be added to this plugin?

**Comment by TxHawks** [comment]
Sorry for taking my time to respond.

I understand the reluctance to implement language specific features outside what general LSP offers for free, so this is probably a no go.

To answer your question though, the JSX elements are those in html-like syntax. In the screenshot they are the `<svg>`, `<use>` and `<VisuallyHidden>` elements (lowercase ones represent native html elements and PascalCase ones custom components). You can see them in the tree generated by simrat39/symbols-outline.nvim on the right, and that they're missing from the `nvim-navic` and `nvim-navbuddy`.

It would have been super helpful for navigation to have them.

![Screenshot 2023-04-01 at 10 49 01](https://user-images.githubusercontent.com/5658514/229273792-3e521b28-073d-42ba-8315-bc30a9185dd8.png)

**Comment by SmiteshP** [comment]
Thanks for explaining the jsx elements 👍🏽 
But yeah, I don't want to add language specific features. Hope you understand.
