### ISSUE TITLE
Error ocured while working with `Nest.js` project

### ISSUE THREAD

**Issue by edr3x** [SmiteshP/nvim-navbuddy#13]
![image](https://user-images.githubusercontent.com/45848083/228019779-5a615c9f-6abb-49c2-8951-b68250d08bc3.png)

I get this error while navigating the project. don't get this error on other languages though.

**Comment by SmiteshP** [comment]
@edr3x Are you upto date on version of nvim-navic?

**Comment by pupbrained** [comment]
I'm getting the same error here, latest commits of navic and navbuddy.
<img width="2008" alt="image" src="https://user-images.githubusercontent.com/33522919/228714570-4a0236cf-87a5-466e-9eae-9c19e993aa77.png">

**Comment by edr3x** [comment]
Mine Got Fixed when i Updated the plugin right now

Thanks for the awesome plugin man! Highly appreciate the good work!!
