### ISSUE TITLE
Prevent opening when pressing `l` on element

### ISSUE THREAD

**Issue by LittleTealeaf** [SmiteshP/nvim-navbuddy#16]
Through my use so far, I've often accidentally opened an element by pressing `l` on it (that is, if it doesn't have any children elements), example as:
![image](https://user-images.githubusercontent.com/35083315/228350768-9b224f69-0ad7-4dc0-8bd4-91e7102d7da3.png)
pressing `l` would close the pane and navigate to that element. A lot of times, I'm pressing keys fast enough that sometimes I do this by mistake.

Would it be possible to either add an option to prevent this ability, or maybe separate into two actions "select child / open" and just "select child"?

**Comment by SmiteshP** [comment]
You can define a custom action function and use that in the config.

```lua
local function children(display)
	if display.focus_node.children == nil then
		-- actions.select(display)
		return
	end

	local child_node
	if display.focus_node.memory then
		child_node = display.focus_node.children[display.focus_node.memory]
	else
		child_node = display.focus_node.children[1]
	end
	display.focus_node = child_node

	display:redraw()
end
```
