### ISSUE TITLE
Set Buffer Filetype

### ISSUE THREAD

**Issue by JamesDevlin5** [SmiteshP/nvim-navbuddy#17]
Would you consider setting the filetype to `navbuddy` or something on open? I'm looking at adding an extension to lualine and it's triggered by filetype

**Comment by SmiteshP** [comment]
What sould filetype of Navbuddy even be? 🤔 
Just txt should be okay I guess?

**Comment by SmiteshP** [comment]
Oh I just saw [this](https://github.com/nvim-telescope/telescope.nvim/blob/e504cf03c24119ee024c4182bee7ab31276cd684/lua/telescope/pickers.lua#L454) in telescope.nvim, figured out plugins can have their own filetype too. Will add one for navbuddy too!

**Comment by JamesDevlin5** [comment]
Yeah, pretty much just triggers an autocommand for Filetype
