### ISSUE TITLE
Is there a way to fuzzy search within the list?

### ISSUE THREAD

**Issue by revelationnow** [SmiteshP/nvim-navbuddy#20]
I have header files with a long list of types and was wondering if there is a good way to do filter on the navbuddy window to quickly find the types that I'm looking for and then investigate them further.

**Comment by bartoszb-rgb** [comment]
Search you were mentioning is not perfect.
I would love to see there fuzzy search filtering. It would be useful for big files.

**Comment by WhoSayIn** [comment]
Yes, came here to post this too.

Amazing plugin btw!

But `/` search is not really doing it. Maybe `fzf` can be integrated?

**Comment by SmiteshP** [comment]
Interesting idea, might be very difficult to implement though 🤔. But yeah I can see the appeal. Perhaps we can leverage Telescope.nvim for fuzzy finding, almost every nvimer has telescope anyways.

**Comment by SmiteshP** [comment]
Hi folks! @revelationnow @WhoSayIn @bartoszb-rgb 
I have implemented a new telescope action. Can you guys checkout the branch `telescope` and check it out. Any feedback would be appreciated 🙌🏽

**Comment by SmiteshP** [comment]
Closing as I created a new action for this.

**Comment by revelationnow** [comment]
Looks good, thanks a lot @SmiteshP!

**Comment by bartoszb-rgb** [comment]
@SmiteshP Looks great! Thanks

**Comment by fecet** [comment]
That's an amazing feature, I have search a whole day for a plugin for telescope breadcrumbs and you save my life! However the current fuzzy search only allow variable names, can we also include their content?
