### ISSUE TITLE
Right panel not rendering

### ISSUE THREAD

**Issue by ColonelPhantom** [SmiteshP/nvim-navbuddy#3]
My navbuddy looks like this: 
![image](https://user-images.githubusercontent.com/7569492/227788901-eb47f408-b96d-4d04-8e2e-9ddefcde7aa2.png)

Any idea what's wrong or what could be the problem?

**Comment by SmiteshP** [comment]
Does this also appear this way when there is text on right panel?
And does the left panel also look like this when empty?
Also there seems to some issue with the border itself, why is it so thick? Try setting border = "none" under window options and let me know if this occurs in that case too.

**Comment by SmiteshP** [comment]
Also try pasting this in your neovim buffer "│", should look like a straight vertical line.
Maybe your font is missing box drawing characters.

**Comment by ColonelPhantom** [comment]
> Does this also appear this way when there is text on right panel?

There is supposed to be text on the right panel, the `sections` dict contains `left, mid, right` but the text is not showing up.



> And does the left panel also look like this when empty?

No, the left panel is colored normally:
![image](https://user-images.githubusercontent.com/7569492/227801882-15169156-4aa1-44d5-845e-45ab3d357ed7.png)


> Also there seems to some issue with the border itself, why is it so thick? Try setting border = "none" under window options and let me know if this occurs in that case too.

This does not help, the right panel is still a gray square:

![image](https://user-images.githubusercontent.com/7569492/227801848-37651235-ef00-4aa8-a259-a933211fa3f1.png)


> Also try pasting this in your neovim buffer "│", should look like a straight vertical line.

This seems to work normally.

**Comment by ColonelPhantom** [comment]
So I just tried some other color schemes, like `desert` (which is built in), and it seems to work with it, but it looks weird. See for yourself:
![image](https://user-images.githubusercontent.com/7569492/227801971-7c720409-c4d6-4c38-9d8f-c39318969e50.png)

The colors on the right pane are completely different than for the other two sections.

**Comment by SmiteshP** [comment]
So added fix for a bug, I wasn't setting left and mid section's border highlight properly. So the issue in the above screenshot should be fixed.

**Comment by SmiteshP** [comment]
In the previous screenshots, the colourscheme you are using, can you check if it has FloatBorder highlight defined. If so it looks like it has foreground and background set to same colour. You could set FloatBorder (or NavbuddyFloatBorder) to have light foreground on dark background for it to look as expected.

**Comment by SmiteshP** [comment]
@ColonelPhantom I made some recent changes as per discussion with author of nui.nvim, hope it has solved this issue. Can you confirm?

**Comment by ColonelPhantom** [comment]
The right pane still is colored slightly differently, but the display is now readable for both of the colorschemes I used in the screenshots above!
