### ISSUE TITLE
bug: auto_attach compatibility with lazy.nvim

### ISSUE THREAD

**Issue by sf8193** [SmiteshP/nvim-navbuddy#30]
with these configs

```
return {
      'SmiteshP/nvim-navbuddy',
      dependencies = {
          'neovim/nvim-lspconfig',
          'SmiteshP/nvim-navic',
          'MunifTanjim/nui.nvim'
      },
      event = 'LspAttach',
      config = {
         lsp = {
            auto_attach = true,
          },
      }
    }
```
```
return {
  'SmiteshP/nvim-navic',
  dependencies = 'neovim/nvim-lspconfig',
  event = 'LspAttach',
  config = {
     lsp = {
        auto_attach = true,
      },
  }
}

```
using lazy, i get an error saying nav buddy doesn't exist. When I add 
```

        if client.server_capabilities.documentSymbolProvider then
          require("nvim-navic").attach(client, bufnr)
          require("nvim-navbuddy").attach(client, bufnr)
        end
```
to my on attach function, it works fine.

**Comment by SmiteshP** [comment]
Hi Guys! @sf8193 @pascalsiemsen 
I haven't yet explored how Lazy.nvim works or stuff. But this seems like something to do with lazy loading the plugin I guess. Looking at both the examples looks like some issue with lazy loading. Can you both try by explicitly asking lazy.nvim to not "lazy load" nvim-navbuddy. (Briefly skimming through the readme I think it can be done via this `lazy = false`, but you guys do check)
If nvim-navbuddy is loading fine when not lazy loaded, then this might be issue with Lazy.nvim.

Still I will soon try to migrate my config from packer to lazy, will try to figure out then.

**Comment by Jxstxs** [comment]
Removing the lazy loading works! Thanks for the hint. I'll try to look into it and figure out if it could be fixed another way.

Also thanks for the plugin! It's adorable.

**Comment by Jxstxs** [comment]
Looks like when you define it as a `dependencies` it will work fine!

**Comment by SmiteshP** [comment]
Hi guys! @pascalsiemsen @sf8193 
I hope the solution pointed out by @Jxstxs works for you guys. Can you confirm?

**Comment by sf8193** [comment]
i think actually my issue was slightly different than the above. Mine works fine as long as i'm not using `autoAttach`, so i don't believe it's an issue with lazy loading (as mine wasn't being loaded lazily with  `config=true`). having said that i just reverted to manually attaching during lspAttach with `event='LspAttach` and it worked well

**Comment by pascalsiemsen** [comment]
I can confirm that `lazy=false` works.
Thanks a lot
