### ISSUE TITLE
Feature Request: Colored Icons

### ISSUE THREAD

**Issue by nikbrunner** [SmiteshP/nvim-navbuddy#33]
Hey there,

love the plugin! This is such an awesome idea!

I thought just as an additional visual quick indicator, colored dev icons would be really cool. I don't know how hard this is to implement, but I thought I should ask at least. :)

**Comment by SmiteshP** [comment]
Hi @nikbrunner !
Not sure I follow the request. The icons as well as the text are already colored (as long as your colorscheme has the highlights defined).

**Comment by SmiteshP** [comment]
Maybe you are using a Colourscheme which doesn't have highlights defined. You can go through the highlights section [here](https://github.com/SmiteshP/nvim-navbuddy/blob/master/doc/navbuddy.txt#L278) to see which highlights you want to set. Or try out themes that have already defined these highlights for example [material.nvim](https://github.com/marko-cerovac/material.nvim)

**Comment by nikbrunner** [comment]
Hi 😄 
Thank you for your Quick Reply!
I apologize. I only looked in the README for the Highlight Groups and not the Help  File. 

I will add these to my Theme. Thank you!
