### ISSUE TITLE
Doesn't open

### ISSUE THREAD

**Issue by jeeeem** [SmiteshP/nvim-navbuddy#40]
Nothing, it does not working for me. No errors, logs or anything, just nada.

Im using latest lunarvim in Windows 11, already tried different config still nothing.
```lua
  {
    "SmiteshP/nvim-navbuddy",
    -- event = "VeryLazy",
    -- event = "LspAttach",
    lazy = false,
    dependencies = "SmiteshP/nvim-navic",
    opts = {
      lsp = {
        auto_attach = true
      }
    }
    -- config = function()
    --   require("nvim-navbuddy").setup{
    --     lsp = { auto_attach = true, preference = { "nvim_lsp", "nvim-cmp", "nvim-lspconfig", "texlab", "lua_ls" } },
    --   }
    -- end,
  },

```

**Comment by SmiteshP** [comment]
Hi @jeeeem !
Do you have lsps for your languages installed and setup? If so can you try attaching to them manually.
Btw, "nvim_lsp", "nvim-cmp" and "nvim-lspconfig" aren't names of any language servers 😅

**Comment by jeeeem** [comment]
> Hi @jeeeem ! Do you have lsps for your languages installed and setup? If so can you try attaching to them manually. Btw, "nvim_lsp", "nvim-cmp" and "nvim-lspconfig" aren't names of any language servers 😅

Oh I just steal it from the other's config, I didnt see that names,but yes, the LSPs are working Im trying it with lua lsp and but nothing happens Im not sure why tho.

**Comment by jeeeem** [comment]
Fixed in discord, using the latest commits in `nvim-navic` solves it.
