### ISSUE TITLE
Query: Any way for navbuddy to ignore some lsp clients ?

### ISSUE THREAD

**Issue by edr3x** [SmiteshP/nvim-navbuddy#47]
as the question says is there any way for navbuddy to ignore some lsp clients line `tailwindcss-ls` or `null-ls` as i got this error:
![2023-04-14_10:10:36](https://user-images.githubusercontent.com/45848083/231944207-4708d109-1fff-42bc-9602-6a2c1a0120c5.png)

was able to solve this by doing this:

```lua

M.on_attach = function(client, bufnr)
    if client.name ~= "tailwindcss" or client.name ~= "null-ls" then
        require("nvim-navbuddy").attach(client, bufnr)
    end
end

```

what i am curious is that is there other better way ?

**Comment by edr3x** [comment]
asking this couz sometimes this works sometimes it doesn't.

**Comment by aaronkollasch** [comment]
Instead of filtering by client name, you could filter by the server's capabilities directly:
```lua
if client.server_capabilities.documentSymbolProvider then
    require("nvim-navbuddy").attach(client, bufnr)
end
```
You can also try using the built-in auto-attach functionality by setting `auto_attach = true` in the [config](https://github.com/SmiteshP/nvim-navbuddy#-customise).

**Comment by edr3x** [comment]
Ohh can do that, Thank you!
