### ISSUE TITLE
Black bar on right side of window for transparent themes

### ISSUE THREAD

**Issue by LittleTealeaf** [SmiteshP/nvim-navbuddy#5]
This plugins is exactly what I need for my workflow, and I'm excited to work with it. However, there appears to be a black horizontal bar to the right of the popup menu

![image](https://user-images.githubusercontent.com/35083315/227790701-69a78d7f-3492-4b8d-aa6f-5aab05873d9a.png)

Which is more noticeable when using a smaller width.

For context, I use a transparent-background theme based on catppuccin, so for many plugins I just override the highlights. I've taken a look into the highlights used with this plugin (at least those that started with `Navbuddy`, but couldn't find any that caused this to happen.

Happy to try various tweaks/updates to figure this out.

**Comment by SmiteshP** [comment]
Ui drawing is completely handled by the nui library by @MunifTanjim.
Not sure what might be the issue, let me try experimenting with transparance settings to see if I can reproduce this.
Meanwhile, can you try setting border = "none" and see if this occurs in that case too?

**Comment by LittleTealeaf** [comment]
Setting border to `none` doesn't get rid of the black bar
![image](https://user-images.githubusercontent.com/35083315/227792178-b2395f89-b218-440b-b20f-59dae0e5f242.png)
I'll also take a look into nui configuration, maybe there's something there

**Comment by SmiteshP** [comment]
> Just had a thought: could that be the scroll-bar?

Not sure nui has scroll bars, and if so I certainly didn't enable them. But if you are using some fancy GUI skin for neovim, that might actually be scroll bar added on.

**Comment by LittleTealeaf** [comment]
I think I've narrowed it down to something with Catppuccin's implementation of transparent backgrounds. I know they have integration with navic, but not with this given how new it is. 

Another thought I had was that it's a shadow, but I tried overriding the `FloatShadow` and `FloatShadowThrough` highlights to no changes

**Comment by MunifTanjim** [comment]
https://github.com/SmiteshP/nvim-navbuddy/blob/61afbf6b2e7a86ff0c88a8535b51ea192146dfc7/lua/nvim-navbuddy/display.lua#L268-L272

https://github.com/SmiteshP/nvim-navbuddy/blob/61afbf6b2e7a86ff0c88a8535b51ea192146dfc7/lua/nvim-navbuddy/init.lua#L8-L23

Percentage doesn't always translate to fill-up the whole area. Instead of using `size` in the last box, try doing `grow = 1`, that'll fill up the remaining space. i.e.

```lua
			nui_layout.Box(right_popup, { grow = 1 }),
```

**Comment by MunifTanjim** [comment]
> I think I've narrowed it down to something with Catppuccin's implementation of transparent backgrounds.

Yeah, that's also the issue here. Normally that black empty space should've been transparent. But this particular theme is rendering the empty space as black.

**Comment by SmiteshP** [comment]
@LittleTealeaf Added fix as per @MunifTanjim's suggestion, can you check if it is fixed
