### ISSUE TITLE
Error: attempt to index upvalue 'v' (a function value)

### ISSUE THREAD

**Issue by hopezh** [SmiteshP/nvim-navbuddy#57]
I got the following error message when trying to use h/j/k/l to navigate in navbuddy:
![image](https://github.com/SmiteshP/nvim-navbuddy/assets/23435810/702b2688-7143-4545-91b1-f2edcfa6bc06)

May I ask what is happening here? and how to fix the issue? 

My neovim config is here (link updated on 17-May): [nvim_navbuddy.lua](https://github.com/hopezh/OatVim/blob/main/after/plugin/nvim_navbuddy.lua).

**Comment by SmiteshP** [comment]
@hopezh @nikbrunner 
There was recently a breaking change in how mappings are set. If you were manually setting the mappings in setup, please refer to the README for how to set them now.

**Comment by SmiteshP** [comment]
@hopezh would have to change it like so

```lua
mappings = {
  ["k"] = actions.next_sibling(),
  ["i"] = actions.previous_sibling(),
  ["j"] = actions.parent(),
  ["l"] = actions.children(),
},
```

**Comment by hopezh** [comment]
> @hopezh would have to change it like so
> 
> ```lua
> mappings = {
>   ["k"] = actions.next_sibling(),
>   ["i"] = actions.previous_sibling(),
>   ["j"] = actions.parent(),
>   ["l"] = actions.children(),
> },
> ```

Your suggestion works like a charm. Thank you very much. I'm enjoying with my "navbuddy" now: 

![image](https://github.com/SmiteshP/nvim-navbuddy/assets/23435810/d7ceac43-6411-44b7-a712-c5c2fdf9017b)

**Comment by SmiteshP** [comment]
Closing as resolved
