### ISSUE TITLE
Custom 'mappings' are not working as expected

### ISSUE THREAD

**Issue by abulwafa** [SmiteshP/nvim-navbuddy#6]
First of all, thank you for this amazing plugin :)

As per the title, adding custom keys to actions does not work as expected;

for ex.       

```lua
["<Left>"] = actions.parent
```

**Comment by athanase** [comment]
I am having the same issue (using neovim nightly and lazy.nvim).
Apart from that, excellent plugin.

**Comment by codewizkid** [comment]
Same here...

**Comment by SmiteshP** [comment]
Should be fixed now.

**Comment by SmiteshP** [comment]
Closing as solved
