### ISSUE TITLE
icons all displaying as question marks

### ISSUE THREAD

**Issue by donhcd** [SmiteshP/nvim-navbuddy#70]
I understand I'm probably missing something very elementary, but can you help me fix this? I tried to install nerdfont to help but adding it doesn't seem to have helped

<img width="175" alt="image" src="https://github.com/SmiteshP/nvim-navbuddy/assets/902007/5ce17f6c-6bd1-400e-936f-c040524f4e41">

here is most of my init.lua

```
require('packer').startup(function(use)
    use 'wbthomason/packer.nvim'

    -- common
    use 'lambdalisue/nerdfont.vim'
    use 'neovim/nvim-lspconfig'
    use {
        "SmiteshP/nvim-navbuddy",
        requires = {
            "neovim/nvim-lspconfig",
            "SmiteshP/nvim-navic",
            "MunifTanjim/nui.nvim",
            "numToStr/Comment.nvim",        -- Optional
            "nvim-telescope/telescope.nvim" -- Optional
        }
    }
end)

local lspconfig = require('lspconfig')
local navbuddy = require("nvim-navbuddy")
lspconfig.tsserver.setup {
    on_attach = function(client, bufnr)
        navbuddy.attach(client, bufnr)
    end
}
lspconfig.pyright.setup {}
lspconfig.gopls.setup {}
lspconfig.rust_analyzer.setup {
    -- Server-specific settings. See `:help lspconfig-setup`
    settings = {
        ['rust-analyzer'] = {},
    },
}
vim.api.nvim_set_keymap('n', '<leader>i', ':Navbuddy<cr>', { noremap = true })
```

**Comment by SmiteshP** [comment]
Issue would be difficult to figure out without knowing more about your setup (OS, what package you used, terminal, etc)
But broadly speaking, make sure that you have changed your terminals font to nerd font. Check guides about setting nerd fonts in your terminal emulator. Some packages of nerd fonts append a NF or NerdFont to the font name (eg: `Input Mono` -> `Input Mono NF`) for indicating the nerdfont variant, check if you are using this variant or not.

Hope this helps, closing as problem is unrelated to the plugins itself.

**Comment by donhcd** [comment]
@SmiteshP thanks for the pointer! got it working after installing nerdfont with brew and following the instructions to add it to my terminal
