### ISSUE TITLE
after change default key mapping, navbuddy asking choice lsp server

### ISSUE THREAD

**Issue by tendertree** [SmiteshP/nvim-navbuddy#79]
currently I'm using mason , and I set the navbuddy attach on tsssever

require("lspconfig").tsserver.setup { capabilities = capabilities, on_attach = function(client, bufnr)
	navbuddy.attach(client, bufnr)
end
}

after I set the default key map. I found navbuddy asking choice lsp Client 
local navbuddy = require("nvim-navbuddy")
local actions = require("nvim-navbuddy.actions")

navbuddy.setup {
	mappings = {
		["o"] = actions.parent(),
		["m"] = actions.children(),
	},
	source_buffer = {
		follow_node = true, -- Keep the current node in focus on the source buffer
		highlight = true, -- Highlight the currently focused node
		reorient = "smart", -- "smart", "top", "mid" or "none"
		scrolloff = nil -- scrolloff value when navbuddy is open
	}
}

[screenshot](https://i.ibb.co/mTLQk9H/2023-08-26-033352.png)

this message only show after override default keymap setting

currently I have three lsp client for typescript (ts server, tailwind , emmet-ls)
I think it is related something but don't know how to fix it 

This is my neovim config file 
https://github.com/tendertree/config/tree/main/data/nvim

**Comment by SmiteshP** [comment]
Hi @tendertree !
I wasn't able to reproduce your issue.. but have added some changes that might help.
Can you checkout if "fix_repeatation" branch fixed your issues?

**Comment by tendertree** [comment]
Thanks :) ! 
after apply "fix_repeatation" branch, it fixed issue :) work out of box :)
