### ISSUE TITLE
Alternative highlighting mode

### ISSUE THREAD

**Issue by Dooez** [SmiteshP/nvim-navbuddy#89]
Default selected line uses inverted colors for highlighting.
I suggest to add an option to use alternative background color and normal text color.

I provide an example of what i mean from Telescope. 
![image](https://github.com/SmiteshP/nvim-navbuddy/assets/29952734/1929dd43-7f02-45ec-9ff5-41dac794f952)

#85 Suggestion possibly achieves this, but I am not sure without an example.

**Comment by SmiteshP** [comment]
I actually added lot of efforts to copy the inverted colors thing from the ranger file manager, I think its looks retro and cool 😆 
But yeah, If someone opens a PR with this changes in backwards compatible way I am okay with it 👍🏽
