### ISSUE TITLE
Don't notify lsp without documentSymbols with Autoattach 

### ISSUE THREAD

**Issue by lkhphuc** [SmiteshP/nvim-navbuddy#9]
As title, would be nice if the lsp_autoattach feature doesn't throw an error for server that not support documentSymbols capability.
At the moment I have 2 error notis for null-ls and copilot for every buffer I enter.

I think a notification when the command is invoked when *no* attached lsp capables of documentSymbols is enough.

Thanks for the great plugin.

**Comment by SmiteshP** [comment]
Added check for this, should be fixed in latest commit. Can you check if it fixes issue for you?

**Comment by lkhphuc** [comment]
Confirmed it fixed. Thanks a lot.

**Comment by Feel-ix-343** [comment]
I am getting this error every time I jump to definition.
