### ISSUE TITLE
how to work

### ISSUE THREAD

**Issue by HughYZJD** [SmiteshP/nvim-navbuddy#91]
Hello everyone, 
When I enter the command: Navbuddy, it can provide some information，When the "l" button is pressed, it does not move to the right panel, but instead closes the pop-up box，Is it a question that I understand？
[
<img width="1089" alt="2" src="https://github.com/SmiteshP/nvim-navbuddy/assets/26761239/ff13619b-6849-4679-987c-7d200f4a9b66">
](url)

**Comment by SmiteshP** [comment]
right box is view only, this is expected
